#!/usr/bin/env bash

set -x

source "${HOME}/bin/ilsutils.sh"

VIMDIR="${HOME}/apps/vim/"

install_featuredeps(){
	# Installs required packages to enable vim features
	#Add X windows clipboard support
	sudo apt-get -y install "libxt-dev"
	# Add Python 3 support, and uncomment
	# CONF_OPT_PYTHON3 = --enable-python3interp in the Makefile
	sudo apt-get -y install "libpython3-dev"
	# Perl support
	sudo apt-get -y install "libperl-dev"
	# Lua support
	sudo apt-get -y install "lua5.4" "liblua5.4-dev"
	# Rugy support
	sudo apt-get -y install "ruby-dev"
	# gpm -For mosue support on Linux console
	sudo apt-get -y install "libgpm-dev"
}

build_vim(){
  estatus=1
	pushd "${VIMDIR}"
	make clean all
	pushd "$VIMDIR"/src
	# Do not know if just "make -j8 1>/dev/null" is preferrable here
	make  -j"$(nproc)" reconfig 1>/dev/null
	# make -j$(nproc) 1>/dev/null
	# make -j$(nproc) test
  make  test || echo "[ERROR] One or more Tests Failed" && estatus=0
	# sudo make install
	popd
	popd
  return $estatus
}

main(){
  bldsuccess=false
  msg="Do you wish to install try to install the required packages to compile?" 
  if confirm "$msg"; then
    install_featuredeps
  fi
  # Careful here was treating confirm and build_vim as if they were inside
  # a test command and was using "-a" to control the logic, obviously wrong ...
  msg="Proceed with VIM compilation?" 
  if confirm "$msg" && build_vim; then
    echo HI
    bldsuccess=true
  fi
  msg="Install VIM?" 
  if "$bldsuccess" && confirm "$msg"; then
    sudo make install
  fi

}

main
